
export const internshipGridColumn = [
    // {
    //     field: "id",
    //     headerName: "User Id",
    //     headerAlign:'center',
    //     width: 130,
    //     type: 'number',
    //     filterable: true,
    //     editable: false,
    //     description: "User ID of intern",
    //     hide: false,
    //     resizable: true,
    // },
    // {
    //     field: "firstName",
    //     headerName: "First name",
    //     headerAlign:'center',
    //     width: 150,
    //     type: 'string',
    //     filterable: true,
    //     editable: true,
    //     description: "First Name of the Intern",
    //     hide: false,
    //     resizable: true,
    // },
    // {
    //     field: "lastName",
    //     headerName: "Last name",
    //     headerAlign:'center',
    //     width: 150,
    //     type: 'string',
    //     filterable: true,
    //     editable: true,
    //     description: "Last Name of the Intern",
    //     hide: false,
    //     resizable: true,
    // },
    // {
    //     field: "age",
    //     headerName: "Age",
    //     headerAlign:'center',
    //     width: 105,
    //     type: 'number',
    //     filterable: true,
    //     editable: true,
    //     description: "Age of the Intern",
    //     hide: false,
    //     resizable: true,
    // },
    // {
    //     field: "role",
    //     headerName: "Role",
    //     headerAlign:'center',
    //     width: 150,
    //     type: 'string',
    //     filterable: true,
    //     editable: true,
    //     description: "Role of the Intern",
    //     hide: false,
    //     resizable: true,
    // },
    // {
    //     field: "email",
    //     headerName: "Email",
    //     headerAlign:'center',
    //     width: 170,
    //     type: 'string',
    //     filterable: true,
    //     editable: true,
    //     description: "Email of the intern",
    //     hide: false,
    //     resizable: true,
    // },
    // {
    //     field: "duration",
    //     headerName: "Duration",
    //     headerAlign:'center',
    //     width: 135,
    //     type: 'string',
    //     filterable: true,
    //     editable: true,
    //     description: "Duration of the Internship",
    //     hide: false,
    //     resizable: true,
    // },
    // {
    //     field: "stipend",
    //     headerName: "Stipend",
    //     headerAlign:'center',
    //     width: 130,
    //     type: 'number',
    //     filterable: true,
    //     editable: true,
    //     description: "Stipend given to the Intern",
    //     hide: false,
    //     resizable: true,
    // },
    // {
    //     field: "contact",
    //     headerName: "Contact",
    //     headerAlign:'center',
    //     width: 130,
    //     type: 'string',
    //     filterable: true,
    //     editable: true,
    //     description: "Contact number of the Intern",
    //     hide: false,
    //     resizable: true,
    // }
    { title: "ID", field: "id", editable: false },
    { title: "First Name", field: "firstName" },
    { title: "Last Name", field: "lastName" },
    {title: "Age", field: "age"},
    {title:"Role",field:"role"},
    { title: "Email", field: "email" },
    {title:"Duration",field:"duration"},
    {title:"Stipend",field:"stipend"},
    { title: "Phone Number", field: "contact"},
    { title: "City", field: "city", }
]

export const internshipGridRow = [
    { id: 1, name: 'IIEP', firstName: "Annam", lastName: "Ruchitha", age: 22, role: 'SDE', email: 'annam@ruchitha.com', duration: '2 months', stipend: '5000', contact: '9876543210' },
    { id: 2, name: 'IIEP', firstName: "Vivek", lastName: "Prajapati", age: 20, role: 'UI Designer', email: 'vivek@prajapati.com', duration: '3 months', stipend: '2000', contact: '9876543210' },
    { id: 3, name: 'IIEP', firstName: "Harshit", lastName: "Riwan", age: 19, role: 'HR', email: 'harshit@riwan.com', duration: '4 months', stipend: '3000', contact: '9876543210' },
    { id: 4, name: 'IIEP', firstName: "Anuj", lastName: "Sachan", age: 23, role: 'UX Designer', email: 'anuj@sachan.com', duration: '2.5 months', stipend: '2500', contact: '9876543210' },
    { id: 5, name: 'IIEP', firstName: "Pankaj", lastName: "Tripathi", age: 22, role: 'Android Developer', email: 'pankaj@tripathi.com', duration: '4 months', stipend: '5500', contact: '9876543210' },
    { id: 6, name: 'IIEP', firstName: "Jitendra", lastName: "Kumar", age: 21, role: 'Django Expert', email: 'jitendra@kumar.com', duration: '2 months', stipend: '5000', contact: '9876543210' },
    { id: 7, firstName: 'Snow', lastName: 'Jon', age: 24, role: 'SDE', email: 'jon@snow.com', duration: '2 months', stipend: 1000, contact: '9876543210', },
    { id: 8, firstName: 'Lannister', lastName: 'Cersei', age: 23, role: 'UX Designer', email: 'cersei@lannister.com', duration: '2 months', stipend: 4000, contact: '9876543210', },
    { id: 9, firstName: 'Lannister', lastName: 'Jaime', age: 22, role: 'Scrum Master', email: 'jaime@lannister.com', duration: '3 months', stipend: 1000, contact: '9876543210', },
    { id: 10, firstName: 'Stark', lastName: 'Arya', age: 21, role: 'Product Manager', email: 'arya@stark.com', duration: '3 months', stipend: 2000, contact: '9876543210', },
    { id: 11, firstName: 'Targaryen', lastName: 'Daenerys', age: 20, role: 'Web Developer', email: 'daenerys@targaryen.com', duration: '4 months', stipend: 3000, contact: '9876543210', },
    { id: 12, firstName: 'Melisandre', lastName: 'Vivek', age: 22, role: 'Backend Developer', email: 'vivek@melisandre.com', duration: '6 months', stipend: 2000, contact: '9876543210', },
    { id: 13, firstName: 'Clifford', lastName: 'Ferrara', age: 23, role: 'Coordinator', email: 'ferrara@cilfford.com', duration: '6 months', stipend: 1000, contact: '9876543210', },
    { id: 14, firstName: 'Frances', lastName: 'Rossini', age: 24, role: 'Digital Marketer', email: 'rossini@frances.com', duration: '3 months', stipend: 5000, contact: '9876543210', },
    { id: 15, firstName: 'Roxie', lastName: 'Harvey', age: 21, role: 'Social Influencer', email: 'harvey@roxie.com', duration: '3 months', stipend: 4000, contact: '9876543210', },
    { id: 16, firstName: 'Viraj', lastName: 'Anime', age: 23, role: 'Product Manager', email: 'vikas@anime.com', duration: '4 months', stipend: 2000, contact: '9876543210', },
    { id: 17, firstName: 'Vikas', lastName: 'Shukla', age: 21, role: 'SDE 1', email: 'harshit@shukla.com', duration: '2 months', stipend: 4000, contact: '9876543210', },
    { id: 18, firstName: 'Abdul', lastName: 'Katiyar', age: 21, role: 'Product Owner', email: 'abdul@katiyar.com', duration: '3 months', stipend: 3000, contact: '9876543210', },
    { id: 19, firstName: 'Ronny', lastName: 'Gupta', age: 21, role: 'Mentor', email: 'ronny@gupta.com', duration: '2 months', stipend: 5000, contact: '9876543210', },
    { id: 20, firstName: 'Avi', lastName: 'Chaudhary', age: 21, role: 'SQL Expert', email: 'avi@chaudhary.com', duration: '1 months', stipend: 2000, contact: '9876543210', },
    { id: 21, firstName: 'Ansh', lastName: 'Khanuja', age: 21, role: 'DataBase Manager', email: 'ansh@khanuja.com', duration: '4 months', stipend: 2000, contact: '9876543210', },
    { id: 22, firstName: 'Ankit', lastName: 'Kumar', age: 21, role: 'Code Reviwer', email: 'ankit@kumar.com', duration: '2 months', stipend: 5000, contact: '9876543210', },
    { id: 23, firstName: 'Jitendra', lastName: 'Chandra', age: 21, role: 'Software Developer', email: 'jitendra@chandra.com', duration: '5 months', stipend: 5000, contact: '9876543210', },
    { id: 24, firstName: 'Poojith', lastName: 'Meena', age: 21, role: 'UI Designer', email: 'poojith@meena.com', duration: '2 months', stipend: 4000, contact: '9876543210', },
    { id: 25, firstName: 'Mukul', lastName: 'Keshri', age: 21, role: 'Data Entry', email: 'mukul@keshri.com', duration: '1 months', stipend: 3000, contact: '9876543210', },
    { id: 26, firstName: 'Aditya', lastName: 'Parit', age: 21, role: 'Data Manager', email: 'aditya@parit.com', duration: '3 months', stipend: 2000, contact: '9876543210', },
    { id: 27, firstName: 'Vinay', lastName: 'Chawla', age: 21, role: 'Role Owner', email: 'vinay@Chawla.com', duration: '6 months', stipend: 1000, contact: '9876543210', },
]

export const internshipGridOptions = {
    title: "Internship Grid",
    row: internshipGridRow,
    column: internshipGridColumn,
    api: "/api/v2/internships",
    enableFilter: true,
}

export default {
    internshipGridColumn,
    internshipGridRow,
    internshipGridOptions
}
